services:
  pipeline_y:
    # image: pipeline-y
    image: ghcr.io/ali2kan/sira-dagster-standard-pipeline:multiarch
    platform: linux/amd64
    # platform: linux/arm64
    hostname: pipeline_y
    environment:
      # DAGSTER_PG_USER: ${DAGSTER_PG_USER}
      # DAGSTER_PG_PASSWORD: ${DAGSTER_PG_PASSWORD}
      # DAGSTER_PG_DB: ${DAGSTER_PG_DB}
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "pipeline-y"
      PIPELINE_NAME: "standard_pipeline"
      GRPC_PORT: "4001"
    expose:
      - "4001"
    ports:
      - "4001:4001"
    networks:
      - dagster_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4001"]
      interval: 10s
      retries: 3

networks:
  dagster_network:
    external: true
    name: dagster_network
